CREATE TYPE "DialysisModality" AS ENUM ('UNKNOWN', 'HEMODIALYSIS', 'PERITONEAL_DIALYSIS', 'CONFLICTING');

ALTER TABLE "UserDialysisStatus"
ADD COLUMN "modality" "DialysisModality" NOT NULL DEFAULT 'UNKNOWN';
