CREATE TYPE "FoodPlanningClass" AS ENUM ('MEAL_ELIGIBLE', 'BEVERAGE_ONLY', 'CONDIMENT', 'INGREDIENT', 'ALCOHOL', 'DESSERT', 'SNACK');

ALTER TABLE "Food"
ADD COLUMN "planningClass" "FoodPlanningClass" NOT NULL DEFAULT 'MEAL_ELIGIBLE';
